/**
 * Adds productivity entries that Andre's AWG_Construction_Productivity
 * Database (V2) was missing — specifically the LF entries for fiber
 * cement trim/fascia/corner pieces, Z-girt rainscreen system,
 * mineral wool board, etc. Without these, the AI estimator was
 * forced to pick SF entries (Fiber Cement Lap) for LF takeoffs and
 * landed on absurd matches like "Backer board — Tile" for fascia.
 *
 * Source: Andre's PROPOSAL KANSO + AWG_Rainscreen_Wall_Assembly
 * spreadsheets generated by Cowork.
 *
 * Idempotent — uses (companyId, divisionName, scopeName) lookup.
 */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const COMPANY_SLUG = 'jmo';

type ExtraEntry = {
  divisionName: string; // Must already exist
  scopeName: string;
  uom: string;
  crew?: string;
  assumedTradeName?: string; // Looked up by name within the company
  mhLow?: number;
  mhAvg: number;
  mhHigh?: number;
  matchCode?: string;
  matchKeywords?: string;
  notes?: string;
};

// Source values cross-referenced with the Cowork PROPOSAL KANSO.xlsx
// (Sections B, C, D) and AWG_Rainscreen_Wall_Assembly.xlsx.
const ENTRIES: ExtraEntry[] = [
  // ===== Fiber cement trim & accessories (Finish Carpentry, LF) =====
  {
    divisionName: 'Finish Carpentry',
    scopeName: 'Fiber cement outside corner trim — 4/4x8',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.04,
    mhAvg: 0.055,
    mhHigh: 0.075,
    matchCode: 'EL02',
    matchKeywords:
      'fiber cement outside corner trim 4/4x8 4/4 fascia hardie',
    notes: 'Cowork Kanso EL02A/EL02B baseline.',
  },
  {
    divisionName: 'Finish Carpentry',
    scopeName: 'Fiber cement fascia board — 4/4x12',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.04,
    mhAvg: 0.055,
    mhHigh: 0.075,
    matchCode: 'EL03',
    matchKeywords:
      'fiber cement fascia board 4/4x12 fascia hardie trim',
    notes: 'Cowork Kanso EL03A/EL03B baseline.',
  },
  {
    divisionName: 'Finish Carpentry',
    scopeName: 'Fiber cement trim — 4/4x12 (wide)',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.04,
    mhAvg: 0.055,
    mhHigh: 0.075,
    matchCode: 'EL04',
    matchKeywords: 'fiber cement trim 4/4x12 wide hardie',
    notes: 'Cowork Kanso EL04 baseline.',
  },
  {
    divisionName: 'Finish Carpentry',
    scopeName: 'Fiber cement trim — 4/4x6 (narrow)',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.025,
    mhAvg: 0.04,
    mhHigh: 0.06,
    matchCode: 'EL11',
    matchKeywords: 'fiber cement trim 4/4x6 narrow hardie',
    notes: 'Cowork Kanso EL11 baseline.',
  },

  // ===== Hardie Lap explicit alias for SF (sheet only had "lap 8.25"") =====
  {
    divisionName: 'Siding',
    scopeName: 'Fiber cement siding — Hardie smooth/cedarmill (any width)',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.04,
    mhAvg: 0.058,
    mhHigh: 0.075,
    matchCode: 'ELFCS',
    matchKeywords:
      'hardie fiber cement siding lap cedarmill smooth elfcs cladding',
    notes: 'Cowork Kanso ELFCS-1..4 baseline.',
  },
  {
    divisionName: 'Siding',
    scopeName: 'Fiber cement shake siding — Hardie',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.05,
    mhAvg: 0.065,
    mhHigh: 0.085,
    matchCode: 'ELFCSS',
    matchKeywords: 'hardie shake siding fiber cement',
    notes: 'Cowork Kanso ELFCSS baseline (shakes slower than lap).',
  },
  {
    divisionName: 'Siding',
    scopeName: 'Fiber cement panel siding — Hardie 4x8',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.05,
    mhAvg: 0.065,
    mhHigh: 0.085,
    matchCode: 'ELFCP',
    matchKeywords: 'hardie panel fiber cement 4x8 cladding',
    notes: 'Cowork Kanso ELFCP baseline.',
  },
  {
    divisionName: 'Siding',
    scopeName: 'Fiber cement soffit panel — Hardie vented',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.04,
    mhAvg: 0.055,
    mhHigh: 0.07,
    matchCode: 'ELFCP-S',
    matchKeywords: 'soffit panel hardie fiber cement vented overhead',
    notes: 'Cowork Kanso ELFCP-S baseline. Overhead slows install.',
  },

  // ===== Rainscreen Z-Girt & furring (Rough Carpentry / Siding crossover) =====
  {
    divisionName: 'Siding',
    scopeName: 'Z-girt thermally broken — install (horizontal 24" OC)',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.08,
    mhAvg: 0.115,
    mhHigh: 0.16,
    matchCode: 'Z-GIRT',
    matchKeywords:
      'z-girt zgirt thermally broken horizontal rainscreen knight clarkdietrich',
    notes: 'Per LF of girt (≈ 1 LF per SF wall @ 24" OC).',
  },
  {
    divisionName: 'Siding',
    scopeName: 'PT 1x3 vertical furring + EPDM tape — install',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Siding Installer',
    mhLow: 0.025,
    mhAvg: 0.035,
    mhHigh: 0.05,
    matchCode: 'FURR',
    matchKeywords:
      'pt 1x3 furring vertical pressure treated epdm tape rainscreen strip',
    notes: 'Tape on bench, fasten through girt to substrate.',
  },
  {
    divisionName: 'Insulation',
    scopeName: 'Mineral wool board — install on wall (4")',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Insulation Installer',
    mhLow: 0.018,
    mhAvg: 0.025,
    mhHigh: 0.035,
    matchCode: 'MWB',
    matchKeywords:
      'mineral wool comfortboard rockwool 4" continuous exterior insulation',
    notes: 'Heavy boards (~50 lb/4x8 @ 4"). Crew of 2 ~180-250 SF/hr.',
  },
  {
    divisionName: 'Insulation',
    scopeName: '2" rigid insulation board — install on wall',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Insulation Installer',
    mhLow: 0.008,
    mhAvg: 0.014,
    mhHigh: 0.022,
    matchCode: 'RIGID',
    matchKeywords:
      'rigid insulation xps eps polyiso 2" continuous exterior board',
    notes: 'XPS/EPS/Polyiso 2", through-fastened.',
  },

  // ===== Flashing & WRB (Air & Water Barriers cluster) =====
  {
    divisionName: 'AVB / WRB',
    scopeName: 'House wrap — Tyvek/equivalent, mech. fastened',
    uom: 'SF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Rough',
    mhLow: 0.004,
    mhAvg: 0.006,
    mhHigh: 0.01,
    matchCode: 'WRB',
    matchKeywords: 'house wrap tyvek wrb air barrier mechanical fastened',
    notes: 'Standard horizontal lap, taped seams not in scope here.',
  },
  {
    divisionName: 'AVB / WRB',
    scopeName: 'Prefinished aluminum flashing — install',
    uom: 'LF',
    crew: '1 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.05,
    mhAvg: 0.07,
    mhHigh: 0.11,
    matchCode: 'FLASH',
    matchKeywords:
      'aluminum flashing prefinished kynar drip edge head wall window door termination',
    notes: 'Hemmed, sealed, lapped.',
  },

  // ===== Guardrails =====
  {
    divisionName: 'Finish Carpentry',
    scopeName: 'Aluminum guardrail — install',
    uom: 'LF',
    crew: '2 Carp',
    assumedTradeName: 'Carpenter — Finish',
    mhLow: 0.3,
    mhAvg: 0.4,
    mhHigh: 0.55,
    matchCode: 'EL07',
    matchKeywords:
      'aluminum guardrail balcony deck railing handrail post infill',
    notes: 'Cowork Kanso EL07 baseline. Includes posts + infill.',
  },
];

(async () => {
  const company = await prisma.company.findUnique({
    where: { slug: COMPANY_SLUG },
    select: { id: true, name: true },
  });
  if (!company) throw new Error('Company jmo not found');

  console.log(`Target: ${company.name}`);

  // Cache divisions + trades by name (case-insensitive)
  const divisions = await prisma.division.findMany({
    where: { companyId: company.id },
  });
  const divByName = new Map(divisions.map((d) => [d.name.toLowerCase(), d]));

  const trades = await prisma.laborTrade.findMany({
    where: { companyId: company.id },
  });
  const tradeByName = new Map(trades.map((t) => [t.name.toLowerCase(), t]));

  let added = 0;
  let updated = 0;
  let skipped = 0;

  for (const e of ENTRIES) {
    const division = divByName.get(e.divisionName.toLowerCase());
    if (!division) {
      console.warn(`  ⚠ Division not found: "${e.divisionName}" — skipping ${e.scopeName}`);
      skipped++;
      continue;
    }
    const trade = e.assumedTradeName
      ? tradeByName.get(e.assumedTradeName.toLowerCase())
      : null;

    const existing = await prisma.productivityEntry.findFirst({
      where: {
        companyId: company.id,
        divisionId: division.id,
        scopeName: e.scopeName,
      },
    });

    const data = {
      companyId: company.id,
      divisionId: division.id,
      scopeName: e.scopeName,
      uom: e.uom,
      crewDescription: e.crew ?? null,
      assumedTradeId: trade?.id ?? null,
      mhPerUnitLow: e.mhLow ?? null,
      mhPerUnitAvg: e.mhAvg,
      mhPerUnitHigh: e.mhHigh ?? null,
      matchCode: e.matchCode ?? null,
      matchKeywords: e.matchKeywords ?? null,
      notes: e.notes ?? null,
    };

    if (existing) {
      await prisma.productivityEntry.update({ where: { id: existing.id }, data });
      updated++;
    } else {
      await prisma.productivityEntry.create({ data });
      added++;
    }
  }

  console.log(`\nDone. Added ${added} · Updated ${updated} · Skipped ${skipped}`);

  const total = await prisma.productivityEntry.count({ where: { companyId: company.id } });
  console.log(`Total productivity entries for ${company.name}: ${total}`);

  await prisma.$disconnect();
})();
